spring.application.name=CustomerService
server.port=8082

# JWT Secret (must match AuthService)
jwt.secret=${JWT_SECRET:your-fallback-secret-key-min-32-chars-long-1234567890}

# AES Secret (must be 16, 24, or 32 bytes)
aes.secret-key=${AES_SECRET:my-secret-key-that-is-32-bytes!}

spring.datasource.url=jdbc:postgresql://localhost:5434/customer_db
spring.datasource.username=customeruser
spring.datasource.password=customerpass123

spring.jpa.hibernate.ddl-auto=update

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true