spring.application.name=KycService
server.port=8084

# JWT Secret (must match AuthService)
jwt.secret=${JWT_SECRET:your-fallback-secret-key-min-32-chars-long-1234567890}

# AES Secret (must be 16, 24, or 32 bytes)
aes.secret-key=${AES_SECRET:my-secret-key-that-is-32-bytes!}

spring.datasource.url=jdbc:postgresql://localhost:5436/kyc_db
spring.datasource.username=kycuser
spring.datasource.password=kycpass123

spring.jpa.hibernate.ddl-auto=update

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# AWS
cloud.aws.credentials.access-key=YOUR_ACCESS_KEY
cloud.aws.credentials.secret-key=YOUR_SECRET_KEY
cloud.aws.region.static=ap-south-1
aws.bucket.name= minibankjava

# Logging configuration to suppress DNS warnings
logging.level.io.netty.resolver.dns=ERROR
logging.level.reactor.netty.http.client=ERROR
